# -*- coding: utf-8 -*-
"""KNNClassifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gYOUrRtXKdB8F1eKTCqjCPJapQ8vpwvj

Importing the necessary Libraries
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

"""Load Dataset"""

# Load dataset
iris = load_iris()
X = iris.data #load the iris data into X (attributes Width and length)
y = iris.target # put the target into Y (Species)

"""Preprocess Data"""

# Split data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features by removing the mean and scaling to unit variance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

"""Implement KNN Classifier



"""

# Initialize the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Predict on the test data
y_pred = knn.predict(X_test)

"""Evaluate the Model

"""

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")