# -*- coding: utf-8 -*-
"""DecisionTrees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcnxsKgv2Qa6DUVQBoOXkztMNM0DXWQe
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Decision Tree classifier
dtree = DecisionTreeClassifier(random_state=42)

# Fit the classifier to the training data
dtree.fit(X_train, y_train)

# Predict the labels for the test data
y_pred = dtree.predict(X_test)

# Calculate and print the accuracy
accuracy = dtree.score(X_test, y_test)
print(f"Accuracy: {accuracy:.2f}")

# Visualize the Decision Tree
plt.figure(figsize=(12, 8))
plot_tree(dtree, feature_names=iris.feature_names, class_names=iris.target_names, filled=True)
plt.show()